$(function(){
    $(".status-all").click(function(){
        $("[name^='status']").prop('checked',true);
    });
});
$(function(){
    $(".priority-all").click(function(){
        $("[name='priority[]']").prop('checked',true);
    });
});