<?php
use Drupal\office\Entity\Employee;
use Drupal\office\x;
if ( ! function_exists('di') ) {
	function di( $obj ) { echo "<pre>"; print_r($obj); echo "</pre>"; }
}


function office_theme() {
	$themes = [];
	$names = [
		'office', 'employee.list', 'employee.view', 'employee.edit',
		'login',
	];
	foreach($names as $name) {

		$themes[ $name ] = [
			'variables' => [ 'data' => null],
			'template' => $name,
		];
	}
	return $themes;
}




function office_preprocess(&$variables, $hook)
{
	$request = \Drupal::request();
	$uri = $request->getRequestUri();
	if ( ! x::isOfficePage() ) return;

	$variables['dir_office'] = drupal_get_path('module', 'office');

	$variables['#attached']['library'][] = 'office/default';
	$variables['data']['class']['office'][] = 'office';
	$variables['data']['class']['office'][] = $hook;

}
