<?php

use Drupal\office\Entity\Group;
use Drupal\office\Entity\Member;
use Drupal\office\Entity\Task;
use Drupal\office\Language;
use Drupal\office\x;

if ( ! function_exists('di') ) {
	function di( $obj ) { echo "<pre>"; print_r($obj); echo "</pre>"; }
}


function office_theme() {
	$themes = [];
	$names = [
		'office', 'login', 'mydesk', 'office.documentation',
		'member.list', 'member.view', 'member.edit',
		'task.edit','task.list', 'task.view',
		'group.edit', 'group.list', 'group.workinghours', 'group.memberlist',
		'attendance.list',
		'process.edit', 'process.list', 'process.view',

	];
	foreach($names as $name) {
		$themes[ $name ] = [
			'variables' => [ 'data' => null],
			'template' => $name,
		];
	}
	return $themes;
}




function office_preprocess(&$variables, $hook)
{
	$request = \Drupal::request();
	$uri = $request->getRequestUri();


	if ( x::in('uid') ) {
		$variables['member'] = Member::loadByUserID(x::in('uid'));
	}

	/**
	 * Office 페이지가 아니면,
	 */
	if ( ! x::isOfficePage() ) {
		if ( $uid = x::myUid() ) {
			$variables['my'] = x::loadEntityByUserID('office_member', $uid);
			$variables['my_group'] = Member::group($uid);
		}
		return;
	}



	$variables['office_module'] = 1;
	$variables['groups'] = Group::loadMultiple();
	$variables['input'] = x::input();
	$variables['priority'] = x::priority();

	$variables['ol'] = Language::load();


	if ( x::myUid() ) x::myOfficeInformation($variables);
	x::officeInformation($variables);

	if ( x::in('code') ) $variables['data']['code'] = x::in('code');
	if ( x::in('message') ) $variables['data']['message'] = x::in('message');

	if ( $hook == 'page' ) {
		// x::gs(2);
	}

	$variables['dir_office'] = drupal_get_path('module', 'office');

	$variables['#attached']['library'][] = 'office/default';
	if ( x::isOfficeMemberPage() ) {
		$variables['#attached']['library'][] = 'office/member';
	}
	else if ( x::isOfficeTaskPage() ) {
		$variables['#attached']['library'][] = 'office/task';
	}
	else if ( x::isOfficeDocumentationPage() ) {
		$variables['#attached']['library'][] = 'office/documentation';
	}
	$variables['data']['class']['office'][] = 'office';

	// page classes
	if ( $hook ) {
		$hook_name = strtolower($hook);
		$hook_name = str_replace('.', '-', $hook_name);
        if ( strpos($hook_name, '-') ) {
            list($pre,$post) = explode('-',$hook_name,2);
            $variables['data']['class']['office'][] = $pre;
            $variables['data']['class']['office'][] = $post;
        }
		$variables['data']['class']['office'][] = $hook_name;
	}

}




